[2025-06-13T05:12:17.093+0000] {processor.py:161} INFO - Started process (PID=1936) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:17.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:12:17.096+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:12:17.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:17.102+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:12:17.100+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
ImportError: cannot import name 'extract_and_save_metrics' from 'extract_clickhouse_metrics' (/opt/airflow/scripts/extract_clickhouse_metrics.py)
[2025-06-13T05:12:17.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:17.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:12:47.442+0000] {processor.py:161} INFO - Started process (PID=1948) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:47.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:12:47.445+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:12:47.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:47.450+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:12:47.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:12:47.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:12:47.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.042 seconds
[2025-06-13T05:13:17.792+0000] {processor.py:161} INFO - Started process (PID=1960) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:17.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:13:17.796+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:13:17.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:17.800+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:13:17.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:13:17.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:17.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:13:48.148+0000] {processor.py:161} INFO - Started process (PID=1972) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:48.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:13:48.151+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:13:48.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:48.156+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:13:48.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:13:48.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:13:48.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.055 seconds
[2025-06-13T05:14:18.546+0000] {processor.py:161} INFO - Started process (PID=1984) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:18.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:14:18.550+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:14:18.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:18.554+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:14:18.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:14:18.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:18.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.039 seconds
[2025-06-13T05:14:48.776+0000] {processor.py:161} INFO - Started process (PID=1996) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:48.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:14:48.779+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:14:48.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:48.783+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:14:48.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:14:48.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:14:48.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:15:19.107+0000] {processor.py:161} INFO - Started process (PID=2014) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:19.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:15:19.111+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:15:19.110+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:19.116+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:15:19.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:15:19.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:19.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.054 seconds
[2025-06-13T05:15:49.494+0000] {processor.py:161} INFO - Started process (PID=2026) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:49.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:15:49.496+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:15:49.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:49.501+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:15:49.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:15:49.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:15:49.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.037 seconds
[2025-06-13T05:16:19.836+0000] {processor.py:161} INFO - Started process (PID=2038) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:19.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:16:19.839+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:16:19.839+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:19.843+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:16:19.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:16:19.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:19.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.033 seconds
[2025-06-13T05:16:50.193+0000] {processor.py:161} INFO - Started process (PID=2050) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:50.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:16:50.196+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:16:50.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:50.200+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:16:50.199+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:16:50.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:16:50.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:17:20.594+0000] {processor.py:161} INFO - Started process (PID=2062) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:20.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:17:20.598+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:17:20.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:20.602+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:17:20.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:17:20.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:20.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.047 seconds
[2025-06-13T05:17:50.958+0000] {processor.py:161} INFO - Started process (PID=2074) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:50.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:17:50.961+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:17:50.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:50.965+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:17:50.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:17:50.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:17:50.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:18:21.310+0000] {processor.py:161} INFO - Started process (PID=2086) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:21.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:18:21.313+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:18:21.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:21.316+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:18:21.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:18:21.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:21.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.037 seconds
[2025-06-13T05:18:51.667+0000] {processor.py:161} INFO - Started process (PID=2098) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:51.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:18:51.670+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:18:51.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:51.674+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:18:51.673+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:18:51.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:18:51.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.049 seconds
[2025-06-13T05:19:22.009+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:22.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:19:22.014+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:19:22.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:22.020+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:19:22.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:19:22.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:22.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.049 seconds
[2025-06-13T05:19:52.394+0000] {processor.py:161} INFO - Started process (PID=2122) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:52.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:19:52.397+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:19:52.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:52.400+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:19:52.399+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:19:52.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:19:52.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:20:22.755+0000] {processor.py:161} INFO - Started process (PID=2134) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:22.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:20:22.758+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:20:22.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:22.762+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:20:22.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:20:22.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:22.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:20:53.109+0000] {processor.py:161} INFO - Started process (PID=2146) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:53.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:20:53.113+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:20:53.112+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:53.117+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:20:53.116+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:20:53.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:20:53.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.042 seconds
[2025-06-13T05:21:23.486+0000] {processor.py:161} INFO - Started process (PID=2158) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:23.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:21:23.490+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:21:23.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:23.493+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:21:23.492+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:21:23.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:23.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:21:53.836+0000] {processor.py:161} INFO - Started process (PID=2170) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:53.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:21:53.838+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:21:53.838+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:53.841+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:21:53.840+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:21:53.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:21:53.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.037 seconds
[2025-06-13T05:22:24.214+0000] {processor.py:161} INFO - Started process (PID=2182) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:24.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:22:24.218+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:22:24.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:24.221+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:22:24.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:22:24.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:24.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:22:54.565+0000] {processor.py:161} INFO - Started process (PID=2194) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:54.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:22:54.569+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:22:54.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:54.573+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:22:54.572+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:22:54.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:22:54.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:23:24.936+0000] {processor.py:161} INFO - Started process (PID=2206) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:24.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:23:24.939+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:23:24.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:24.943+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:23:24.942+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:23:24.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:24.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:23:55.516+0000] {processor.py:161} INFO - Started process (PID=2218) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:55.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:23:55.519+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:23:55.519+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:55.522+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:23:55.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:23:55.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:23:55.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:24:25.942+0000] {processor.py:161} INFO - Started process (PID=2230) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:25.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:24:25.944+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:24:25.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:25.948+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:24:25.946+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:24:25.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:25.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:24:56.257+0000] {processor.py:161} INFO - Started process (PID=2240) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:56.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:24:56.260+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:24:56.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:56.264+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:24:56.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:24:56.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:24:56.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.042 seconds
[2025-06-13T05:25:26.629+0000] {processor.py:161} INFO - Started process (PID=2252) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:26.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:25:26.632+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:25:26.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:26.636+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:25:26.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:25:26.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:26.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:25:56.969+0000] {processor.py:161} INFO - Started process (PID=2264) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:56.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:25:56.972+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:25:56.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:56.976+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:25:56.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:25:56.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:25:56.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:26:27.336+0000] {processor.py:161} INFO - Started process (PID=2277) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:27.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:26:27.340+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:26:27.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:27.344+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:26:27.342+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:26:27.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:27.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.047 seconds
[2025-06-13T05:26:57.693+0000] {processor.py:161} INFO - Started process (PID=2289) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:57.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:26:57.697+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:26:57.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:57.700+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:26:57.699+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:26:57.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:26:57.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:27:28.061+0000] {processor.py:161} INFO - Started process (PID=2301) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:28.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:27:28.064+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:27:28.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:28.067+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:27:28.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:27:28.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:28.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:27:58.449+0000] {processor.py:161} INFO - Started process (PID=2313) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:58.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:27:58.452+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:27:58.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:58.457+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:27:58.455+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:27:58.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:27:58.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.039 seconds
[2025-06-13T05:28:28.805+0000] {processor.py:161} INFO - Started process (PID=2325) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:28.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:28:28.808+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:28:28.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:28.812+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:28:28.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:28:28.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:28.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:28:59.154+0000] {processor.py:161} INFO - Started process (PID=2337) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:59.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:28:59.157+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:28:59.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:59.161+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:28:59.160+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:28:59.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:28:59.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:29:29.535+0000] {processor.py:161} INFO - Started process (PID=2349) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:29.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:29:29.539+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:29:29.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:29.544+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:29:29.542+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:29:29.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:29.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:29:59.907+0000] {processor.py:161} INFO - Started process (PID=2361) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:59.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:29:59.911+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:29:59.911+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:59.918+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:29:59.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:29:59.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:29:59.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.047 seconds
[2025-06-13T05:30:30.279+0000] {processor.py:161} INFO - Started process (PID=2373) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:30:30.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:30:30.283+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:30:30.282+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:30:30.287+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:30:30.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:30:30.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:30:30.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:31:00.656+0000] {processor.py:161} INFO - Started process (PID=2385) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:00.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:31:00.659+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:31:00.658+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:00.664+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:31:00.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:31:00.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:00.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.049 seconds
[2025-06-13T05:31:31.031+0000] {processor.py:161} INFO - Started process (PID=2397) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:31.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:31:31.034+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:31:31.034+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:31.038+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:31:31.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:31:31.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:31:31.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.039 seconds
[2025-06-13T05:40:16.098+0000] {processor.py:161} INFO - Started process (PID=2406) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:16.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:40:16.105+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:40:16.104+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:16.112+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:40:16.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:40:16.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:16.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.140 seconds
[2025-06-13T05:40:46.326+0000] {processor.py:161} INFO - Started process (PID=2418) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:46.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:40:46.329+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:40:46.329+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:46.332+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:40:46.331+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:40:46.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:40:46.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:41:16.971+0000] {processor.py:161} INFO - Started process (PID=2430) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:16.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:41:16.975+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:41:16.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:16.978+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:41:16.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:41:16.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:17.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T05:41:47.366+0000] {processor.py:161} INFO - Started process (PID=2442) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:47.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:41:47.369+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:41:47.369+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:47.374+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:41:47.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:41:47.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:41:47.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.042 seconds
[2025-06-13T05:42:17.812+0000] {processor.py:161} INFO - Started process (PID=2454) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:17.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:42:17.815+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:42:17.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:17.819+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:42:17.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:42:17.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:17.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:42:48.225+0000] {processor.py:161} INFO - Started process (PID=2466) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:48.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:42:48.228+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:42:48.228+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:48.232+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:42:48.231+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:42:48.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:42:48.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.045 seconds
[2025-06-13T05:43:18.632+0000] {processor.py:161} INFO - Started process (PID=2478) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:18.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:43:18.637+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:43:18.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:18.642+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:43:18.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:43:18.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:18.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.053 seconds
[2025-06-13T05:43:49.003+0000] {processor.py:161} INFO - Started process (PID=2490) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:49.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:43:49.010+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:43:49.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:49.019+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:43:49.017+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:43:49.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:43:49.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:44:19.438+0000] {processor.py:161} INFO - Started process (PID=2502) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:19.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:44:19.441+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:44:19.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:19.445+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:44:19.443+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:44:19.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:19.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:44:49.859+0000] {processor.py:161} INFO - Started process (PID=2514) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:49.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:44:49.862+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:44:49.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:49.866+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:44:49.864+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:44:49.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:44:49.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:45:20.249+0000] {processor.py:161} INFO - Started process (PID=2526) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:20.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:45:20.253+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:45:20.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:20.256+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:45:20.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:45:20.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:20.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T05:45:50.647+0000] {processor.py:161} INFO - Started process (PID=2538) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:50.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:45:50.650+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:45:50.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:50.653+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:45:50.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:45:50.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:45:50.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:46:21.071+0000] {processor.py:161} INFO - Started process (PID=2550) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:21.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:46:21.073+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:46:21.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:21.077+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:46:21.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:46:21.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:21.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.035 seconds
[2025-06-13T05:46:51.467+0000] {processor.py:161} INFO - Started process (PID=2562) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:51.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:46:51.470+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:46:51.470+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:51.474+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:46:51.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:46:51.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:46:51.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:47:21.905+0000] {processor.py:161} INFO - Started process (PID=2574) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:21.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:47:21.908+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:47:21.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:21.913+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:47:21.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:47:21.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:21.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.043 seconds
[2025-06-13T05:47:52.344+0000] {processor.py:161} INFO - Started process (PID=2586) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:52.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:47:52.346+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:47:52.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:52.350+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:47:52.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:47:52.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:47:52.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:48:22.713+0000] {processor.py:161} INFO - Started process (PID=2598) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:22.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:48:22.717+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:48:22.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:22.721+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:48:22.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:48:22.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:22.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.042 seconds
[2025-06-13T05:48:53.098+0000] {processor.py:161} INFO - Started process (PID=2610) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:53.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:48:53.101+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:48:53.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:53.105+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:48:53.104+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:48:53.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:48:53.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:49:23.496+0000] {processor.py:161} INFO - Started process (PID=2622) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:23.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:49:23.500+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:49:23.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:23.504+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:49:23.502+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:49:23.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:23.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:49:53.925+0000] {processor.py:161} INFO - Started process (PID=2634) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:53.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:49:53.928+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:49:53.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:53.931+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:49:53.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:49:53.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:49:53.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T05:50:24.379+0000] {processor.py:161} INFO - Started process (PID=2646) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:24.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:50:24.383+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:50:24.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:24.387+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:50:24.386+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:50:24.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:24.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.037 seconds
[2025-06-13T05:50:54.808+0000] {processor.py:161} INFO - Started process (PID=2658) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:54.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:50:54.811+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:50:54.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:54.814+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:50:54.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:50:54.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:50:54.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:51:25.226+0000] {processor.py:161} INFO - Started process (PID=2670) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:25.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:51:25.229+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:51:25.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:25.235+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:51:25.233+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:51:25.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:25.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T05:51:55.676+0000] {processor.py:161} INFO - Started process (PID=2682) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:55.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:51:55.680+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:51:55.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:55.684+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:51:55.683+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:51:55.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:51:55.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.045 seconds
[2025-06-13T05:52:26.075+0000] {processor.py:161} INFO - Started process (PID=2694) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:26.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:52:26.079+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:52:26.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:26.084+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:52:26.083+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:52:26.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:26.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:52:56.463+0000] {processor.py:161} INFO - Started process (PID=2706) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:56.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:52:56.467+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:52:56.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:56.473+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:52:56.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:52:56.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:52:56.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.045 seconds
[2025-06-13T05:53:26.544+0000] {processor.py:161} INFO - Started process (PID=2718) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:26.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:53:26.548+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:53:26.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:26.552+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:53:26.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:53:26.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:26.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.048 seconds
[2025-06-13T05:53:56.657+0000] {processor.py:161} INFO - Started process (PID=2730) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:56.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:53:56.660+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:53:56.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:56.663+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:53:56.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:53:56.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:53:56.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.031 seconds
[2025-06-13T05:54:27.090+0000] {processor.py:161} INFO - Started process (PID=2742) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:27.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:54:27.093+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:54:27.093+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:27.100+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:54:27.096+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:54:27.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:27.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:54:57.528+0000] {processor.py:161} INFO - Started process (PID=2754) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:57.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:54:57.532+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:54:57.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:57.536+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:54:57.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:54:57.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:54:57.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T05:55:27.983+0000] {processor.py:161} INFO - Started process (PID=2766) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:27.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:55:27.986+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:55:27.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:27.989+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:55:27.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:55:27.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:28.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.039 seconds
[2025-06-13T05:55:58.374+0000] {processor.py:161} INFO - Started process (PID=2778) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:58.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:55:58.378+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:55:58.378+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:58.383+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:55:58.381+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:55:58.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:55:58.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.045 seconds
[2025-06-13T05:56:28.688+0000] {processor.py:161} INFO - Started process (PID=2788) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:28.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:56:28.693+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:56:28.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:28.697+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:56:28.696+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:56:28.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:28.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T05:56:59.078+0000] {processor.py:161} INFO - Started process (PID=2800) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:59.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:56:59.081+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:56:59.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:59.085+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:56:59.083+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:56:59.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:56:59.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:57:29.460+0000] {processor.py:161} INFO - Started process (PID=2812) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:57:29.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:57:29.465+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:57:29.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:57:29.469+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:57:29.468+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:57:29.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:57:29.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.043 seconds
[2025-06-13T05:58:00.058+0000] {processor.py:161} INFO - Started process (PID=2824) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:00.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:58:00.062+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:58:00.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:00.066+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:58:00.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:58:00.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:00.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.045 seconds
[2025-06-13T05:58:30.499+0000] {processor.py:161} INFO - Started process (PID=2836) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:30.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:58:30.502+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:58:30.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:30.505+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:58:30.504+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:58:30.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:58:30.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T05:59:00.928+0000] {processor.py:161} INFO - Started process (PID=2848) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:00.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:59:00.932+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:59:00.931+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:00.936+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:59:00.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:59:00.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:00.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T05:59:31.344+0000] {processor.py:161} INFO - Started process (PID=2860) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:31.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T05:59:31.346+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:59:31.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:31.350+0000] {logging_mixin.py:188} INFO - [2025-06-13T05:59:31.349+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T05:59:31.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T05:59:31.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T06:00:01.735+0000] {processor.py:161} INFO - Started process (PID=2872) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:01.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:00:01.740+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:00:01.739+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:01.745+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:00:01.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:00:01.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:01.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.050 seconds
[2025-06-13T06:00:32.144+0000] {processor.py:161} INFO - Started process (PID=2884) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:32.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:00:32.147+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:00:32.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:32.151+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:00:32.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:00:32.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:00:32.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.037 seconds
[2025-06-13T06:01:02.560+0000] {processor.py:161} INFO - Started process (PID=2896) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:02.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:01:02.563+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:01:02.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:02.569+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:01:02.567+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:01:02.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:02.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.047 seconds
[2025-06-13T06:01:32.929+0000] {processor.py:161} INFO - Started process (PID=2908) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:32.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:01:32.933+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:01:32.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:32.937+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:01:32.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:01:32.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:01:32.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T06:02:03.360+0000] {processor.py:161} INFO - Started process (PID=2920) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:03.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:02:03.364+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:02:03.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:03.369+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:02:03.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:02:03.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:03.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T06:02:33.781+0000] {processor.py:161} INFO - Started process (PID=2932) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:33.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:02:33.785+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:02:33.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:33.788+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:02:33.787+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:02:33.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:02:33.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T06:03:03.862+0000] {processor.py:161} INFO - Started process (PID=2944) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:03.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:03:03.867+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:03:03.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:03.871+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:03:03.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:03:03.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:03.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.038 seconds
[2025-06-13T06:03:34.269+0000] {processor.py:161} INFO - Started process (PID=2956) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:34.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:03:34.274+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:03:34.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:34.278+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:03:34.276+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:03:34.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:03:34.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T06:04:04.665+0000] {processor.py:161} INFO - Started process (PID=2968) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:04.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:04:04.669+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:04:04.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:04.672+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:04:04.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:04:04.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:04.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.044 seconds
[2025-06-13T06:04:35.044+0000] {processor.py:161} INFO - Started process (PID=2980) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:35.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:04:35.049+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:04:35.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:35.055+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:04:35.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:04:35.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:04:35.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.051 seconds
[2025-06-13T06:05:05.190+0000] {processor.py:161} INFO - Started process (PID=2992) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:05.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:05:05.193+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:05:05.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:05.197+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:05:05.195+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:05:05.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:05.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.034 seconds
[2025-06-13T06:05:35.283+0000] {processor.py:161} INFO - Started process (PID=3004) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:35.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:05:35.286+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:05:35.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:35.290+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:05:35.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver'
[2025-06-13T06:05:35.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:05:35.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.039 seconds
[2025-06-13T06:52:56.084+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:52:56.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:52:56.089+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:52:56.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:52:56.105+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:52:56.102+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:52:56.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:52:56.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.056 seconds
[2025-06-13T06:53:27.151+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:27.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:53:27.174+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:53:27.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:27.178+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:53:27.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:53:27.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:27.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.060 seconds
[2025-06-13T06:53:57.636+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:57.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:53:57.639+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:53:57.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:57.643+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:53:57.642+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:53:57.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:53:57.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.048 seconds
[2025-06-13T06:54:28.026+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:28.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:54:28.029+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:54:28.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:28.036+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:54:28.034+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:54:28.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:28.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.050 seconds
[2025-06-13T06:54:58.413+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:58.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:54:58.418+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:54:58.417+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:58.430+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:54:58.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:54:58.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:54:58.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.062 seconds
[2025-06-13T06:55:31.878+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:55:31.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:55:31.881+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:55:31.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:55:31.887+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:55:31.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:55:31.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:55:31.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.041 seconds
[2025-06-13T06:56:02.662+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:02.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:56:02.666+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:56:02.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:02.672+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:56:02.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:56:02.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:02.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.048 seconds
[2025-06-13T06:56:33.053+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:33.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:56:33.057+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:56:33.057+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:33.062+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:56:33.060+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:56:33.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:56:33.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.049 seconds
[2025-06-13T06:57:03.418+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:03.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:57:03.423+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:57:03.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:03.428+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:57:03.426+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:57:03.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:03.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.046 seconds
[2025-06-13T06:57:33.924+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:33.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:57:33.927+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:57:33.926+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:33.930+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:57:33.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:57:33.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:57:33.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T06:58:04.408+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:04.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:58:04.412+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:58:04.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:04.416+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:58:04.415+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:58:04.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:04.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.043 seconds
[2025-06-13T06:58:34.767+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:34.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:58:34.770+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:58:34.770+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:34.775+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:58:34.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:58:34.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:58:34.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.040 seconds
[2025-06-13T06:59:05.187+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:05.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:59:05.189+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:59:05.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:05.193+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:59:05.192+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:59:05.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:05.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.036 seconds
[2025-06-13T06:59:32.645+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:32.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hourly_clickhouse_metrics_dag.py for tasks to queue
[2025-06-13T06:59:32.654+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:59:32.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:32.661+0000] {logging_mixin.py:188} INFO - [2025-06-13T06:59:32.658+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hourly_clickhouse_metrics_dag.py", line 8, in <module>
    from extract_clickhouse_metrics import extract_and_save_metrics
  File "/opt/airflow/scripts/extract_clickhouse_metrics.py", line 1, in <module>
    import clickhouse_connect
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-13T06:59:32.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hourly_clickhouse_metrics_dag.py
[2025-06-13T06:59:32.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hourly_clickhouse_metrics_dag.py took 0.062 seconds
